title: "Nic's Blog"
description: "Philosophical musics & software learnings"
baseurl: "/blog"
url: "https://shinysquirl.github.io"
theme: minima

sass:
  style: compressed

plugins:
  - jekyll-sass-converter