title: "Nic's Blog"
description: "Philosophical musings & software learnings"
baseurl: "/blog" 
url: "https://shinysquirl.github.io"
theme: minima

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sass-converter

markdown: kramdown
highlighter: rouge