title: Nic's Blog
description: Philisophical musics & software learnings
baseurl: "/blog"
url: "https://chinesecroll.github.io"
theme: minima

sass:
  style: compressed

# Ensure the following line is included to tell Jekyll to look for assets in the right place
plugins:
  - jekyll-sass-converter